### ISSUE TITLE
[Bug]: After update 1.12.5 does not work in the mobile version of obsidian (android)

### ISSUE THREAD

**Issue by antomal** [st3v3nmw/obsidian-spaced-repetition#1033]
### Describe the bug

Just updated the plugin to version 1.12.5 and now I can't open the cards and the queue selection window! :-(

### To Reproduce

1. Update plugin version to 1.12.5
2. Try to open the card list or queue

### Expected behavior

I should see a window with lists of cards or a window with tags on pages (queue)

### OS of your device

MIUI 13.0.6

### Obsidian version

1.6.7 (149)

### Plugin version

1.12.5

**Comment by ronzulu** [comment]
Hi @antomal 

We'll need a more comprehensive description of what fails, including screenshots.

It seems fine on my Samsung Android

Cheers
Ronny

![2024-08-01 20 58 25](https://github.com/user-attachments/assets/4d93dc1d-6d39-4c77-bd1a-c1e6441ed6f7)
![2024-08-01 20 58 39](https://github.com/user-attachments/assets/b3e19ece-25d2-4d6d-a930-aea0f8e1dab7)
![2024-08-01 20 58 46](https://github.com/user-attachments/assets/0bbd91ad-cbb6-46db-b062-b6b1fabba25f)
![2024-08-01 20 58 53](https://github.com/user-attachments/assets/9abcdf03-cb93-4f51-a9bc-c7eeb457237b)
![2024-08-01 20 59 01](https://github.com/user-attachments/assets/e339513b-329a-4b5b-b6e9-ed9d03a5a12b)

**Comment by antomal** [comment]
I'm happy to help, but I don't know how to describe in more detail and make screenshots of what is not there.

But I'll try. I recorded a video from the screen.
https://static.antomal.com/Screenrecorder-2024-08-01-14-17-27-933.mp4

1. first I show that the version is 1.12.4 and everything works
2. I update the plugin to 1.12.5
3. I try to open window "Review flashcards" - nothing happens
4. I try to open command "Spaced Repetition: Open a note for review" - nothing...

**Comment by ronzulu** [comment]
Sorry, I don't have much expertise on an android platform.

If this was on the desktop, I'd suggest opening the chrome developer window (control shift I) and see if there is any error output.

I did a Google search, but couldn't find an easy way to do this on Android. One way that involves connecting the phone to a PC is shown here (but I haven't tried it)
https://help.pushwoosh.com/hc/en-us/articles/360027726731-Android-Chrome-console-logs

**Comment by antomal** [comment]
I'm very sorry to hear that. :-(

I tested previous versions, maybe there are ideas and this will help.

1.12.0 — NOT working (only menu Review Flashcards takes a looooong time to open. the queue selection window does not open)
1.12.1 — NOT working (only menu Review Flashcards takes a looooong time to open. the queue selection window does not open)
1.12.2 — NOT working
1.12.3 — working (!!!)
1.12.4 — working (!!!)
1.12.5 — NOT working


I have a smartphone Redmi note 11
Screen resolution — 2400×1080 (aspect ratio — 20:9)
There may be some problem with opening interface windows due to non-standard (narrow) aspect ratio…


Just in case, I'll leave it here — Android version — 12SKQ1.211103.001

**Comment by ronzulu** [comment]
Thanks for doing that. If you can do the same thing with the different beta releases, that would also be helpful.

After 1.12.4 there were 4 beta releases that incrementally incorporated the changes that were released as part of 1.12.5. (not precisely, but is a good starting point)

Please try:
https://github.com/ronzulu/obsidian-spaced-repetition/releases/tag/1.13-beta.5
https://github.com/ronzulu/obsidian-spaced-repetition/releases/tag/1.13-beta.6
https://github.com/ronzulu/obsidian-spaced-repetition/releases/tag/1.13-beta.7
https://github.com/ronzulu/obsidian-spaced-repetition/releases/tag/1.13-beta.8

Don't worry that the beta is 1.13 but the mainstream release is 1.12.5

**Comment by antomal** [comment]
No problem!

1.13-beta.5 — working
1.13-beta.6 — Command "Open note for review" opens an EMPTY window. "Review flashcards (Decks) — works well. (see screenshots)
1.13-beta.7 — working
1.13-beta.8 — NOT working (!!!)

![Screenshot_2024-08-02-18-07-34-792_md obsidian](https://github.com/user-attachments/assets/93a37b93-3499-4154-aa03-b4b48131bfc2)
![Screenshot_2024-08-02-18-07-57-576_md obsidian](https://github.com/user-attachments/assets/df33060f-0375-4955-97e8-394904a6983a)


I'm glad to help you.

**Comment by ronzulu** [comment]
That is helpful.
At this stage we don't know if it's a code issue or a rendering issue.

Could you next please try:

main.js/manifest.json | styles.css
- | -
1.13-beta.7 | 1.13-beta.8
1.13-beta.8 | 1.13-beta.7

Hopefully that will give us a clue.

Cheers
Ronny

**Comment by antomal** [comment]
I checked!

main.js/manifest.json | styles.css | ?
-- | -- | --
1.13-beta.7 | 1.13-beta.8 | working
1.13-beta.8 | 1.13-beta.7 | **NOT** working

**Comment by ronzulu** [comment]
Hi @antomal 

Could you please try the latest beta release https://github.com/ronzulu/obsidian-spaced-repetition/releases/tag/1.13-beta.12

The bug should still occur, but hopefully we can capture the exception details.

Use the new log to file setting:
![image](https://github.com/user-attachments/assets/c3ca69c6-7d9e-447c-b1ad-20c34fcf5248)

Then try one of the operations that fail, and a log file will appear in the vault under folder `temp/logs`

Cheers
Ronny

**Comment by antomal** [comment]
- Command "Open note for review" opens an EMPTY window (screenshot)
- Review flashcards" (Decks) — NOT working

<img src="https://github.com/user-attachments/assets/ac897b48-0fc6-4eaf-b2d9-289ccf271311" width="200">



log:
```
[2024-08-06 18:30:33]: 
---
## Obsidian: SpacedRepetition: Branch: master v1.13-beta.12

[2024-08-06 18:30:42]: 
---
## Obsidian: SpacedRepetition: Branch: master v1.13-beta.12

[2024-08-06 18:30:46]: ERROR: sync()
[2024-08-06 18:30:46]: STACK: TypeError: Cannot read properties of undefined (reading 'normalize')
    at isEqualOrSubPath (plugin:obsidian-spaced-repetition:6658:44)
    at eval (plugin:obsidian-spaced-repetition:6981:58)
    at Array.some (<anonymous>)
    at _SettingsUtil.isPathInNoteIgnoreFolder (plugin:obsidian-spaced-repetition:6981:41)
    at OsrAppCore.loadVault (plugin:obsidian-spaced-repetition:10524:26)
    at _SRPlugin.doSync (plugin:obsidian-spaced-repetition:23880:27)
    at _SRPlugin.sync (plugin:obsidian-spaced-repetition:23869:18)
    at eval (plugin:obsidian-spaced-repetition:23674:22)
[2024-08-06 18:30:48]: ERROR: sync()
[2024-08-06 18:30:48]: STACK: TypeError: Cannot read properties of undefined (reading 'normalize')
    at isEqualOrSubPath (plugin:obsidian-spaced-repetition:6658:44)
    at eval (plugin:obsidian-spaced-repetition:6981:58)
    at Array.some (<anonymous>)
    at _SettingsUtil.isPathInNoteIgnoreFolder (plugin:obsidian-spaced-repetition:6981:41)
    at OsrAppCore.loadVault (plugin:obsidian-spaced-repetition:10524:26)
    at _SRPlugin.doSync (plugin:obsidian-spaced-repetition:23880:27)
    at _SRPlugin.sync (plugin:obsidian-spaced-repetition:23869:18)
    at Object.callback (plugin:obsidian-spaced-repetition:23722:22)
    at aY (http://localhost/app.js:1:2045224)
    at t.onChooseItem (http://localhost/app.js:1:2637292)
[2024-08-06 18:31:01]: ERROR: sync()
[2024-08-06 18:31:01]: STACK: TypeError: Cannot read properties of undefined (reading 'normalize')
    at isEqualOrSubPath (plugin:obsidian-spaced-repetition:6658:44)
    at eval (plugin:obsidian-spaced-repetition:6981:58)
    at Array.some (<anonymous>)
    at _SettingsUtil.isPathInNoteIgnoreFolder (plugin:obsidian-spaced-repetition:6981:41)
    at OsrAppCore.loadVault (plugin:obsidian-spaced-repetition:10524:26)
    at _SRPlugin.doSync (plugin:obsidian-spaced-repetition:23880:27)
    at _SRPlugin.sync (plugin:obsidian-spaced-repetition:23869:18)
    at Object.eval [as callback] (plugin:obsidian-spaced-repetition:23658:20)
    at http://localhost/app.js:1:2372501
    at e.handleEvent (http://localhost/app.js:1:1174276)
[2024-08-06 18:31:01]: Unhandled promise rejection: TypeError: Cannot read properties of undefined (reading 'getDeck')
[2024-08-06 18:31:48]: 
---
## Obsidian: SpacedRepetition: Branch: master v1.13-beta.12

[2024-08-06 18:31:51]: ERROR: sync()
[2024-08-06 18:31:51]: STACK: TypeError: Cannot read properties of undefined (reading 'normalize')
    at isEqualOrSubPath (plugin:obsidian-spaced-repetition:6658:44)
    at eval (plugin:obsidian-spaced-repetition:6981:58)
    at Array.some (<anonymous>)
    at _SettingsUtil.isPathInNoteIgnoreFolder (plugin:obsidian-spaced-repetition:6981:41)
    at OsrAppCore.loadVault (plugin:obsidian-spaced-repetition:10524:26)
    at _SRPlugin.doSync (plugin:obsidian-spaced-repetition:23880:27)
    at _SRPlugin.sync (plugin:obsidian-spaced-repetition:23869:18)
    at eval (plugin:obsidian-spaced-repetition:23674:22)
```

**Comment by ronzulu** [comment]
Great, now we know why.

[ [FIX] Folder ignore sorts all folder starting with string #972 ](https://github.com/st3v3nmw/obsidian-spaced-repetition/pull/972) introduced a call to the system api `normalize`, which exists on the Desktop, but not on some (all?) mobile platforms.

@4Source, are you able to update the `isEqualOrSubPath` code to not depend on the `normalize` function.

Ideally the project's build process should detect this condition and fail.

**Comment by 4Source** [comment]
> @4Source, are you able to update the `isEqualOrSubPath` code to not depend on the `normalize` function.

I will take a look at it should be possible

Sry for late response

**Comment by ronzulu** [comment]
This is now part of the latest beta release:
https://github.com/st3v3nmw/obsidian-spaced-repetition/discussions/1011
