### ISSUE TITLE
[Bug]: Note review pane not showing notes for future dates

### ISSUE THREAD

**Issue by dmantisk** [st3v3nmw/obsidian-spaced-repetition#1074]
### Describe the bug

This issue seems inconsistent, and only appeared since the last update (1.12.6)
I'm not sure if this one is only a problem on my end.

By default, all the notes I need to review for 'today' are shown correctly.
But any notes for 'tomorrow', other dates, and 'new' are not shown.
![image](https://github.com/user-attachments/assets/0db1526e-757b-4da9-ab8e-1c8d6e7c1c1e)
Note that 'New' and 'Thursday' are expanded, but empty.

However, (randomly) opening different notes causes some of the empty notes to show. _Sometimes_.
![image](https://github.com/user-attachments/assets/f4dd49c5-1042-49b2-bcac-2dabd98545a4)
Note that 'New' is now visible, but 'Thursday' is still empty.

Both the requirement of number of notes/specific notes to open before the empty list starts showing seems to be different each time.
Which of the expanded segments of the review pane shows up also seems to be semi random. The first few I keep expanded seems to get priority, but it seems to not work.

### To Reproduce

1. Tag a note to mark it for note review
2. Review it as hard, good, or easy (doesn't matter what)
3. Check the date for when it will come up again
4. Close the note/switch to another note
5. Restart Obsidian
6. Go to review pane
7. Try expanding the date from (3)

### Expected behavior

All the notes for future dates being visible from the start, or being consistently regenerated by resetting the review pane or something.

### OS of your device

Win10

### Obsidian version

1.6.7

### Plugin version

1.12.6

### Installer version

1.6.5

### Config file

[data.json](https://github.com/user-attachments/files/17023076/data.json)

This issue isn't file specific, but I'm uploading the file I used to reproduce this on a new note
The tag `#BT` is used here to identify this note for note review
The content is irrelevant
[Untitled.md](https://github.com/user-attachments/files/17023082/Untitled.md)

**Comment by WillPascucci** [comment]
Hello, I am having the same issue. Only notes scheduled for the current day are shown correctly. I am experiencing roughly the same behavior as OP. Whenever I explicitly open a note that should be shown, it will then appear in the dropdown.

I have noticed that whenever the SR Sync operation is done (whatever function creates this console message in debug mode "SR: Sync took 12ms"), the note review pane will refresh. Meaning, that if I find the files to fill out the dropdown by clicking on the file, they will disappear again (the bug will occur) on that SR: Sync operation.

In the console, I noticed this error message, but I'm not sure if it is related or not.
` TypeError: this.noteReviewQueue.reviewDecks is not iterable
    at ReviewQueueListView.redraw (plugin:obsidian-spaced-repetition:15426:56)
    at eval (plugin:obsidian-spaced-repetition:15403:70)
    at e.tryTrigger (app.js:1:723190)
    at e.trigger (app.js:1:723123)
    at t.trigger (app.js:1:2283688)
    at t.activeLeafEvents (app.js:1:2269215)
    at l (app.js:1:522936)
    at c (app.js:1:523052)`

I was poking around in the console, but I'm not very familiar with JS/TS. I was just looking at the error though and changed line 15426 to (adding the underscore to reviewDecks)
`    for (const [deckKey, deck] of this.noteReviewQueue._reviewDecks) {`

that fixed the console error message, but not the issue. could be 100% unrelated, but figured I'd mention

**Comment by jtaylor100** [comment]
I have the same bug and did a bit of debugging, just on why the 'New' cards aren't showing.

This line: https://github.com/st3v3nmw/obsidian-spaced-repetition/blob/master/src/gui/review-queue-list-view.tsx#L93 seems to evaluate to false for the cards I am expecting to render but are missing.

Because it evaluates to false and is passed into the parameter 'hidden', the card is added to the list but has `display: none` set to it.

`t("NEW")` evaluates to 'New' with my current locale settings and `deck.activeFolders` contains `['#review', 'Today']`. This is despite in my GUI I can see the 'New' and 'Yesterday' folders are expanded (with the arrow to the left of the title pointed down, instead of right). Maybe 'activeFolders' isn't meant to imply they are expanded, but I'm unsure.

So a theory could be that 'deck.activeFolders' isn't being populated properly -- but if files are re-appearing when we navigate to them, this wouldn't make sense.

As a horrific workaround, when I use the SR plugin I am opening the dev tools and deleting this snippet of code:
https://github.com/st3v3nmw/obsidian-spaced-repetition/blob/master/src/gui/review-queue-list-view.tsx#L208C1-L210C10 so that all cards appear all of the time. It breaks expanding the items, but I'd prefer that to this bug.

**Comment by dmantisk** [comment]
Updating to version 1.30.0 broke the plugin (It completely disappeared despite restarting or re-enabling it).

However, it was fixed when I reinstalled the plugin. And now the note review pane is displaying all the dates as well! The oldest technique in technology lol.

@wpasc @jtaylor100 If you still have the issue try reinstalling the plugin.
